version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: share.sh
      timeout: 300
  ApplicationStart:
    - location: start.sh
      timeout: 300
